# Generated by Django 4.1.7 on 2023-03-13 22:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=50)),
                ('date_foundation', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1800), main.models.max_value_current_year])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('S', 'Shoes'), ('O', 'Outerwear'), ('P', 'Pants')], max_length=1)),
                ('cart_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('release', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
    ]
