# Generated by Django 4.1.7 on 2023-04-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sorted_product',
            field=models.BooleanField(default=False),
        ),
    ]
