# Generated by Django 4.1.7 on 2023-03-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('W', 'Man'), ('M', 'Woman'), ('U', 'Unisex')], default='U', max_length=1),
        ),
    ]
