# Generated by Django 4.1.7 on 2023-04-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_sorted_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sorted_product',
        ),
    ]
