# Generated by Django 4.1.7 on 2023-04-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_favoritelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
