# Generated by Django 4.1.7 on 2023-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_favoritelist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritelist',
            name='products',
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='products',
            field=models.ManyToManyField(to='main.product'),
        ),
    ]
