# Generated by Django 4.1.7 on 2023-03-26 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_item_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.CharField(choices=[('S', 'Shoes'), ('O', 'Outerwear'), ('P', 'Pants')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=250)),
                ('cart_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('W', 'Man'), ('M', 'Woman'), ('U', 'Unisex')], default='U', max_length=1)),
                ('release', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='name_company',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
