# Generated by Django 4.1.7 on 2023-03-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_product_sizeproduct_remove_item_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
