# Generated by Django 4.1.7 on 2023-03-26 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_product_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=250)),
                ('image_prev', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('W', 'Man'), ('M', 'Woman'), ('U', 'Unisex')], default='U', max_length=1)),
                ('release', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('product_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
