# Generated by Django 4.1.7 on 2023-04-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_purchases_purchase_rename_reviews_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.review')),
            ],
        ),
    ]
