# Generated by Django 4.1.7 on 2023-04-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_purchase_city_purchase_postcode_purchase_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_list',
            field=models.CharField(default='test', max_length=250),
        ),
    ]
