# Generated by Django 4.1.7 on 2023-04-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_company_image_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image_list',
            field=models.CharField(max_length=250),
        ),
    ]
