# Generated by Django 4.1.7 on 2023-04-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_image_list_company_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sizes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.productsize'),
        ),
    ]
