# Generated by Django 4.1.7 on 2023-04-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_purchase_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='sizes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productsize'),
        ),
    ]
