# Generated by Django 4.1.7 on 2023-04-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_purchase_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.JSONField(default={}),
        ),
    ]
