# Generated by Django 4.1.7 on 2023-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_purchase_sizes_remove_purchase_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
