# Generated by Django 4.1.7 on 2023-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_purchase_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='check_products',
            field=models.ManyToManyField(to='main.product'),
        ),
    ]
